# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

GoLoginUser = com.mvc.crud.action.user.GoLoginUserAction

####Routing User####
GoHomeUser = com.mvc.crud.action.user.GoHomeUserAction
GoAkunSaya = com.mvc.crud.action.user.GoAkunSayaAction
GoUbahProfil = com.mvc.crud.action.user.GoUbahProfilAction
UpdateUser=com.mvc.crud.action.user.UpdateUserAction
LogoutUser=com.mvc.crud.action.user.LogoutUserAction
GoHapusAkunSaya=com.mvc.crud.action.user.GoHapusAkunSayaAction
GoRegisterUser = com.mvc.crud.action.user.GoRegisterUserAction
RegisterUser = com.mvc.crud.action.user.RegisterUserAction
LogoutUser=com.mvc.crud.action.user.LogoutUserAction
#GoTopUp = com.mvc.crud.action.user.GoTopUpAction          
#ProsesTopUp = com.mvc.crud.action.user.ProsesTopUpAction

####Routing Bioskop####
GoListBioskop = com.mvc.crud.action.bioskop.GoListBioskopAction
GoDetailBioskop=com.mvc.crud.action.bioskop.GoDetailBioskopAction

####Routing Film####
GoDetailFilm=com.mvc.crud.action.film.GoDetailFilmAction

####Routing Kursi & Order####
GoPilihKursi=com.mvc.crud.action.order.GoPilihKursiAction

########Routing Payment####
GoToPayment=com.mvc.crud.action.payment.GoPaymentAction
ProcessPayment=com.mvc.crud.action.payment.ProcessPaymentAction
PaymentSukses = com.mvc.crud.action.payment.PaymentSuksesAction
PaymentGagal = com.mvc.crud.action.payment.PaymentGagalAction

####Routing TWallet####
GoTopUp = com.mvc.crud.action.twallet.GoTopUpAction
ProsesTopUp = com.mvc.crud.action.twallet.ProsesTopUpAction
GoTopUpSukses = com.mvc.crud.action.twallet.GoTopUpSuksesAction

####Routing Tiket Saya####
GoTiketSaya = com.mvc.crud.action.tiket.GoTiketSayaAction
GoCetakTiket = com.mvc.crud.action.tiket.GoCetakTiketAction